[package]
name = "massa_execution_exports"
version = "0.23.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
displaydoc = "0.2"
thiserror = "1.0"
num = { version = "0.4", features = ["serde"] }
parking_lot = { version = "0.12", features = [
    "deadlock_detection",
], optional = true }
tempfile = { version = "3.3", optional = true }
tokio = { version = "1.23", features = ["sync"] }
mockall = { version = "0.11.4",  optional = true}

# custom modules
massa-proto-rs = { git = "https://github.com/massalabs/massa-proto-rs", rev = "0c277c2" }
massa_hash = { path = "../massa-hash" }
massa_models = { path = "../massa-models" }
massa_time = { path = "../massa-time" }
massa_storage = { path = "../massa-storage" }
massa_final_state = { path = "../massa-final-state" }
massa_ledger_exports = { path = "../massa-ledger-exports", optional = true }
massa_module_cache = { path = "../massa-module-cache" }
massa_versioning = { path = "../massa-versioning" }
massa-sc-runtime = { git = "https://github.com/massalabs/massa-sc-runtime", branch = "main" }

[dev-dependencies]
mockall = "0.11.4"

# for more information on what are the following features used for, see the cargo.toml at workspace level

[features]
gas_calibration = ["massa_ledger_exports/testing", "parking_lot", "tempfile"]
testing = ["massa_models/testing", "massa_ledger_exports/testing", "parking_lot", "tempfile", "mockall"]
