[workspace]
members = [
  "massa-api",
  "massa-api-exports",
  "massa-async-pool",
  "massa-bootstrap",
  "massa-client",
  "massa-cipher",
  "massa-consensus-exports",
  "massa-consensus-worker",
  "massa-db",
  "massa-executed-ops",
  "massa-execution-exports",
  "massa-execution-worker",
  "massa-factory-exports",
  "massa-factory-worker",
  "massa-channel",
  "massa-consensus-exports",
  "massa-consensus-worker",
  "massa-hash",
  "massa-logging",
  "massa-metrics",
  "massa-models",
  "massa-node",
  "massa-sdk",
  "massa-storage",
  "massa-pool-worker",
  "massa-pool-exports",
  "massa-protocol-exports",
  "massa-protocol-worker",
  "massa-module-cache",
  "massa-serialization",
  "massa-signature",
  "massa-time",
  "massa-wallet",
  "massa-ledger-worker",
  "massa-ledger-exports",
  "massa-final-state",
  "massa-pos-exports",
  "massa-pos-worker",
  "massa-versioning",
  "massa-grpc",
  "massa-xtask",
]
resolver = "2"

# From https://doc.rust-lang.org/cargo/reference/profiles.html#overrides
[profile.dev.package."*"]
opt-level = 3 # Speed-up the CI

# # Features
#
# * testing: enable some tests specific exports.
# Usage: add testing = ["massa_crate/testing", ...] to dev-dependencies to use test specific functions avaible in massa-crate.
# Do not add as a regular dependency. Never.
#
# * sandbox: for testing purpose, genesis timestamps is set as now + 9 seconds.
# The saved snapshot can then be used to restart the network from the snapshot.
