[package]
name = "massa_protocol_worker"
version = "0.23.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

[dependencies]
tracing = {version =  "0.1", features = ["log"]}
rand = "0.8"
parking_lot = "0.12"
crossbeam = "0.8"
serde_json = "1.0"
nom = "=7.1"
num_enum = "0.5"
# TODO tag peernet version
peernet = { git = "https://github.com/massalabs/PeerNet", branch = "use_stream_limiter" } #rev = "bf8adf5" }
tempfile = { version = "3.3", optional = true } # use with testing feature
rayon = "1.7.0"
schnellru = "0.2.1"

# modules Custom
massa_hash = { path = "../massa-hash" }
massa_models = { path = "../massa-models" }
massa_logging = { path = "../massa-logging" }
massa_protocol_exports = { path = "../massa-protocol-exports" }
massa_consensus_exports = { path = "../massa-consensus-exports" }
massa_pool_exports = { path = "../massa-pool-exports" }
massa_storage = { path = "../massa-storage" }
massa_serialization = { path = "../massa-serialization" }
massa_signature = { path = "../massa-signature" }
massa_time = { path = "../massa-time" }
massa_versioning = { path = "../massa-versioning" }

[dev-dependencies]
tempfile = "3.3"
serial_test = "2.0.0"

[features]
testing = ["massa_protocol_exports/testing", "tempfile", "massa_pool_exports/testing", "massa_consensus_exports/testing"]
