[package]
name = "massa_ledger_exports"
version = "0.23.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

[dependencies]
displaydoc = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = { version = "3.3", optional = true }    # use with testing feature
thiserror = "1.0"
nom = "=7.1"
rocksdb = "0.20"
num_enum = "0.5.10"

# custom modules
massa-proto-rs = { git = "https://github.com/massalabs/massa-proto-rs", rev = "c9a6079" }
massa_hash = { path = "../massa-hash" }
massa_models = { path = "../massa-models" }
massa_serialization = { path = "../massa-serialization" }
massa_db = { path = "../massa-db" }



# for more information on what are the following features used for, see the cargo.toml at workspace level
[features]
testing = ["tempfile", "massa_models/testing"]
